project:
  type: website
  output-dir: docs
  resources:
    - "assets/*.pdf"

website:
  title: "Bhabilsh Limbu"
  favicon: assets/logo.png
  
  navbar:
    background: primary 
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: CV / Resume
    right:
      - icon: github
        href: https://github.com/lims2026
      - icon: linkedin
        href: https://www.linkedin.com/in/bhabilsh-l-1200771b1/

  page-footer:
    background: primary
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/bhabilsh-l-1200771b1/
      - icon: github
        href: https://github.com/lims2026
      - icon: envelope
        href: "mailto:limbubhabilsh@gmail.com"

format:
  html:
    theme: Zephyr
    css: styles.css